version: "3"
services:
  api:
    build: .
    ports:
        - 8000:8000
    # env_file:
    #     - ./.env
    environment:
      - DATABASE_HOSTNAME=aws-0-us-east-1.pooler.supabase.com
      - DATABASE_PORT=6543
      - DATABASE_PASSWORD=Harshit6203731746
      - DATABASE_NAME=postgres
      - DATABASE_USERNAME=postgres.vjyeyurjikqcejcjbose
      - SECRET_KEY=eriutgvhenrtyi8geryerwtvgh9er67tehqr4678tbgr8r7rty78n45v78t45n0674bvn
      - ALGORITHIM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=60
